apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-twislock-development
  namespace: flux-system
spec:
  interval: 1m
  path: ./overlays/development/infrastructure/twislock
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
