replicaCount: 1
service:
  type: ClusterIP
  port: 9000
  consolePort: 9001
persistence:
  enabled: true
  size: 20Gi
  storageClass: gp2
accessKey: "minioadmin"
secretKey: "minioadminsecret"
image:
  repository: minio/minio
  tag: "RELEASE.2025-09-05T00-00-00Z"
