apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-external-secrets-production
  namespace: flux-system
spec:
  interval: 1m
  path: ./overlays/production/infrastructure/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
