apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-tenant-values
  namespace: minio-prod
data:
  tenant-prod.yaml: |
    tenant:
      name: minio-tenant
      namespace: minio-prod
      pools:
        - name: pool-0
          servers: 2
          volumesPerServer: 1
          size: 10Gi
          storageClassName: hostpath
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: v1.min.io/tenant
                          operator: In
                          values: ["minio-tenant"]
                    topologyKey: kubernetes.io/hostname
      certificate:
        requestAutoCert: true
      configuration:
        name: minio-tenant-env
      configSecret:
        name: minio-tenant-env
        existingSecret: true
      ingress:
        api:
          enabled: false
        console:
          enabled: false
      resources:
        requests:
          cpu: "250m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    metrics:
      enabled: true
