apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-prod
spec:
  interval: 10m
  releaseName: minio-tenant
  chart:
    spec:
      chart: tenant
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: minio-tenant-values
      valuesKey: tenant-prod.yaml
  values: {}
