apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 10m
  releaseName: minio-operator
  chart:
    spec:
      chart: operator
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    operators:
      replicaCount: 2
    console:
      ingress:
        enabled: false
