apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "minio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["server", "/data"]
          ports:
            - containerPort: {{ .Values.service.port }}
              name: api
            - containerPort: {{ .Values.service.consolePort }}
              name: console
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.accessKey | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.secretKey | quote }}
